### PR TITLE
[WIP] Restructure site to allow multiple events stored in /data/events

### PR DESCRIPTION
**Pull request by bastilian**
This allows us to have multiple events in the data directory.

The event sites themselves have minor changes and have the top header to be global and a sub-navigation that is in the event context.

Sneak-peek of the index page: 
screen shot 2015-05-13 at 14 26 34

Every suggestion on how to improve the index page and event pages are of course welcome and appreciated!

### CODE REVIEW

**Comment by FloorD** [comment]
oeehhhhh pwetty! 
I have a ton of copy for the Berlin page. :sparkling_heart:

**Comment by alicetragedy** [comment]
I'm just checking out the pull request locally, and here are my thoughts:

_index page_
- I think the header photos should be black & white. the past event headers could have one main image of the crowd at the event or something. the future events could just have a city header, if that works, or a picture of the set location.
- remove links to eventbrite/meetup, or move them to the relevant event (vienna)
- eventually, the email addresses in the code of conduct should be removed (if people start organising their own events, contacting people from the core team regarding breaches of the CoC at local events will not be useful.)
- once the organisers' kit is ready, we could add a link to it under the event banners (eg. "Want to organise your own ROSSConf in your city? Here is our organiser's kit!")
- I noticed that there is only a hover effect on the Berlin banner, but not on the Vienna one. haven't investigated further.
- eventually, once we have more events, I could see the index page being divided between future events and past events, but right now it's totally fine like this, as separating them now would look lächerlich.

_event page_
- adding "this was ROSSConf [city name]" section to past event pages, with photo-gallery or links to photos, to blog posts, etc..
- each event page would need its own meetup/tickets link as well as contact information for the 'chapter' (event).

I think that's all – let me know if I can help implementing some of this.

**Comment by bastilian** [comment]
it's mergable.

I've made a few improvements based on @alicetragedy's suggestion. will continue to improve, but let's get berlin live! :)

**Comment by alicetragedy** [comment]
@bastilian ohhhhh yay! can I merge? #yolo

**Comment by bastilian** [comment]
e174af15fe2adbaf387368c010007ac6ff6568cfa41948a0d1fd7c1afe736e42

**Pull request merged**
