### PR TITLE
[WIP] Site Updates

### PR DESCRIPTION
**Pull request by bastilian**
I'm going to use this PR to track a number of updates.
- [x] Fix Logo
- [x] Add testimonials to frontpage (see also #16)
- [ ] Update site design
- Polish Blog
  - [x] Post-pages
  - [ ] RSS-Feed
  - [x] Disqus comments

### CODE REVIEW

**Comment by bastilian** [comment]
Logo is now fixed:

screen shot 2015-08-23 at 11 04 37
screen shot 2015-08-23 at 11 05 02

**Comment by bastilian** [comment]
Testimonials appear on the frontpage as follows:

screen shot 2015-08-23 at 13 18 49

**Comment by alicetragedy** [comment]
:+1: 
I like the testimonials with the photo in the background. Looking good! (judging by the screenshots – did not pull locally)

**Comment by bastilian** [comment]
@alicetragedy these are the images pulled from FB with high-res it will look way better

**Comment by bastilian** [comment]
Page of a blog post looks like this:

kicking off rossconf berlin come improve ruby open source with us rossconf

**Comment by bastilian** [comment]
It might look a bit sad now, but will look better when more articles are published. ... or worse. we'll see...

The blog-index page:
rossconf

**Comment by alicetragedy** [comment]
I think it looks pretty awesome! I'm really curious what it will look like once there are more posts, too. :sparkles:

**Comment by alicetragedy** [comment]
Is there a fallback for the header if there isn't one for a post, or do we always have to add one?

**Comment by bastilian** [comment]
@alicetragedy no header is the fallback.

**Comment by bastilian** [comment]
If this and #31 is merged the blog page would look like this:

rossconf

**Pull request merged**
